// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"bookstore/bookstore/config"
	"bookstore/bookstore/controller"
	"bookstore/bookstore/dao"
	"bookstore/bookstore/mysql"
	"bookstore/bookstore/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateApp() (*Application, error) {
	viper := config.NewConfig()
	db := mysql.NewDB(viper)
	bookDao := dao.NewBookDaoImpl(db)
	bookService := service.NewBookServiceImpl(bookDao)
	bookController := controller.NewBookController(bookService)
	userDao := dao.NewUserDaoImpl(db)
	userService := service.NewUserServiceImpl(userDao)
	userController := controller.NewUserController(userService)
	loginController := controller.NewLoginController(userService)
	application := NewApplication(viper, bookController, userController, loginController)
	return application, nil
}

// wire.go:

var ProviderSet = wire.NewSet(dao.ProviderSet, service.ProviderSet, controller.ProviderSet, config.NewConfig, mysql.NewDB)
